services:
  freqtrade_webserver2:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      freqtrade webserver

  freqtrade_dev2:
    build: .
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"

    command: >
      freqtrade recursive-analysis
      --config /freqtrade/user_data/config.json
      --strategy MyStrategy
      --timerange=20250101-20250820
